// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Juwon.Models
{
    public partial class APPInfo
    {
        [Key]
        public int ID { get; set; }
        [StringLength(5)]
        public string Type { get; set; }
        public int? VesionApp { get; set; }
        [StringLength(100)]
        public string UrlApp { get; set; }
        [StringLength(100)]
        public string ReleaseNotes { get; set; }
        [StringLength(100)]
        public string Name { get; set; }
    }
}