// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Juwon.Models
{
    public partial class Area
    {
        public Area()
        {
            Location = new HashSet<Location>();
        }

        [Key]
        public int AreaId { get; set; }
        [Required]
        [StringLength(50)]
        public string AreaName { get; set; }
        public int AreaCategoryId { get; set; }
        [StringLength(100)]
        public string AreaDescription { get; set; }
        [Required]
        public bool? Active { get; set; }
        [Column(TypeName = "datetime2(0)")]
        public DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        [Column(TypeName = "datetime2(0)")]
        public DateTime? ModifiedDate { get; set; }
        public int? ModifiedBy { get; set; }

        [ForeignKey(nameof(AreaCategoryId))]
        [InverseProperty("Area")]
        public virtual AreaCategory AreaCategory { get; set; }
        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(UserInfo.Area))]
        public virtual UserInfo CreatedByNavigation { get; set; }
        [InverseProperty("Area")]
        public virtual ICollection<Location> Location { get; set; }
    }
}