// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Juwon.Models
{
    public partial class Bom
    {
        public Bom()
        {
            BomDetail = new HashSet<BomDetail>();
        }

        [Key]
        public int BomId { get; set; }
        [Required]
        [StringLength(15)]
        public string BomCode { get; set; }
        public int MoldId { get; set; }
        [StringLength(100)]
        public string FileUpload { get; set; }
        [Required]
        public bool? Active { get; set; }
        [Column(TypeName = "datetime2(0)")]
        public DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        [Column(TypeName = "datetime2(0)")]
        public DateTime? ModifiedDate { get; set; }
        public int? ModifiedBy { get; set; }

        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(UserInfo.Bom))]
        public virtual UserInfo CreatedByNavigation { get; set; }
        [ForeignKey(nameof(MoldId))]
        [InverseProperty("Bom")]
        public virtual Mold Mold { get; set; }
        [InverseProperty("Bom")]
        public virtual ICollection<BomDetail> BomDetail { get; set; }
    }
}