// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Juwon.Models
{
    public partial class BomDetail
    {
        [Key]
        public int BomDetailId { get; set; }
        public int BomId { get; set; }
        public int PartId { get; set; }
        public int QCMasterId { get; set; }
        public int MaterialId { get; set; }
        [Column(TypeName = "decimal(5, 5)")]
        public decimal? Weight { get; set; }
        public short Amount { get; set; }
        [StringLength(100)]
        public string Image { get; set; }
        [Required]
        public bool? Active { get; set; }
        [Column(TypeName = "datetime2(0)")]
        public DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        [Column(TypeName = "datetime2(0)")]
        public DateTime? ModifiedDate { get; set; }
        public int? ModifiedBy { get; set; }

        [ForeignKey(nameof(BomId))]
        [InverseProperty("BomDetail")]
        public virtual Bom Bom { get; set; }
        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(UserInfo.BomDetailCreatedByNavigation))]
        public virtual UserInfo CreatedByNavigation { get; set; }
        [ForeignKey(nameof(MaterialId))]
        [InverseProperty(nameof(UserInfo.BomDetailMaterial))]
        public virtual UserInfo Material { get; set; }
        [ForeignKey(nameof(PartId))]
        [InverseProperty("BomDetail")]
        public virtual Part Part { get; set; }
        [ForeignKey(nameof(QCMasterId))]
        [InverseProperty("BomDetail")]
        public virtual QCMaster QCMaster { get; set; }
    }
}