// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Juwon.Models
{
    public partial class Buyer
    {
        public Buyer()
        {
            VendorBuyerRel = new HashSet<VendorBuyerRel>();
        }

        [Key]
        public int BuyerId { get; set; }
        [Required]
        [StringLength(20)]
        public string BuyerCode { get; set; }
        [Required]
        [StringLength(100)]
        public string BuyerName { get; set; }
        [StringLength(100)]
        public string BuyerUrl { get; set; }
        [StringLength(100)]
        public string BuyerEmail { get; set; }
        [StringLength(20)]
        public string BuyerPhone { get; set; }
        [StringLength(100)]
        public string BuyerDescription { get; set; }
        [Required]
        public bool? Active { get; set; }
        [Column(TypeName = "datetime2(0)")]
        public DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        [Column(TypeName = "datetime2(0)")]
        public DateTime? ModifiedDate { get; set; }
        public int? ModifiedBy { get; set; }

        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(UserInfo.Buyer))]
        public virtual UserInfo CreatedByNavigation { get; set; }
        [InverseProperty("Buyer")]
        public virtual ICollection<VendorBuyerRel> VendorBuyerRel { get; set; }
    }
}