// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Juwon.Models
{
    public partial class Color
    {
        public Color()
        {
            Material = new HashSet<Material>();
        }

        [Key]
        public int ColorId { get; set; }
        [Required]
        [StringLength(20)]
        public string ColorCode { get; set; }
        [Required]
        [StringLength(100)]
        public string ColorName { get; set; }
        [StringLength(100)]
        public string ColorDescription { get; set; }
        [Required]
        public bool? Active { get; set; }
        [Column(TypeName = "datetime2(0)")]
        public DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        [Column(TypeName = "datetime2(0)")]
        public DateTime? ModifiedDate { get; set; }
        public int? ModifiedBy { get; set; }

        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(UserInfo.Color))]
        public virtual UserInfo CreatedByNavigation { get; set; }
        [InverseProperty("Color")]
        public virtual ICollection<Material> Material { get; set; }
    }
}