// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Juwon.Models
{
    public partial class CommonDetail
    {
        public CommonDetail()
        {
            MaterialMaterialInOut = new HashSet<Material>();
            MaterialMaterialSection = new HashSet<Material>();
            MaterialMaterialType = new HashSet<Material>();
            MaterialMaterialUnit = new HashSet<Material>();
        }

        [Key]
        public int ID { get; set; }
        [Required]
        [StringLength(4)]
        public string Code { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
        [StringLength(4)]
        public string MasterCode { get; set; }
        public bool? Active { get; set; }

        [InverseProperty(nameof(Material.MaterialInOut))]
        public virtual ICollection<Material> MaterialMaterialInOut { get; set; }
        [InverseProperty(nameof(Material.MaterialSection))]
        public virtual ICollection<Material> MaterialMaterialSection { get; set; }
        [InverseProperty(nameof(Material.MaterialType))]
        public virtual ICollection<Material> MaterialMaterialType { get; set; }
        [InverseProperty(nameof(Material.MaterialUnit))]
        public virtual ICollection<Material> MaterialMaterialUnit { get; set; }
    }
}