// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Juwon.Models
{
    public partial class CommonMaster
    {
        [Key]
        public int ID { get; set; }
        [Required]
        [StringLength(4)]
        public string Code { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
        public bool? Active { get; set; }
    }
}