// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Juwon.Models
{
    public partial class Location
    {
        [Key]
        public int LocationId { get; set; }
        [Required]
        [StringLength(50)]
        public string LocationName { get; set; }
        [StringLength(100)]
        public string LocationDescription { get; set; }
        public int LocationCategoryId { get; set; }
        public int AreaId { get; set; }
        [Required]
        public bool? Active { get; set; }
        [Column(TypeName = "datetime2(0)")]
        public DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        [Column(TypeName = "datetime2(0)")]
        public DateTime? ModifiedDate { get; set; }
        public int? ModifiedBy { get; set; }

        [ForeignKey(nameof(AreaId))]
        [InverseProperty("Location")]
        public virtual Area Area { get; set; }
        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(UserInfo.Location))]
        public virtual UserInfo CreatedByNavigation { get; set; }
        [ForeignKey(nameof(LocationCategoryId))]
        [InverseProperty("Location")]
        public virtual LocationCategory LocationCategory { get; set; }
    }
}