// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Juwon.Models
{
    public partial class LocationCategory
    {
        public LocationCategory()
        {
            Location = new HashSet<Location>();
        }

        [Key]
        public int LocationCategoryId { get; set; }
        [Required]
        [StringLength(50)]
        public string LocationCategoryName { get; set; }
        [Required]
        public bool? Active { get; set; }
        [Column(TypeName = "datetime2(0)")]
        public DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        [Column(TypeName = "datetime2(0)")]
        public DateTime? ModifiedDate { get; set; }
        public int? ModifiedBy { get; set; }

        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(UserInfo.LocationCategory))]
        public virtual UserInfo CreatedByNavigation { get; set; }
        [InverseProperty("LocationCategory")]
        public virtual ICollection<Location> Location { get; set; }
    }
}