// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Juwon.Models
{
    public partial class MenuUserGuide
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        public string Content { get; set; }
        [Required]
        [StringLength(12)]
        public string MenuCode { get; set; }
        public int MenuLevel { get; set; }
        [Required]
        [StringLength(2)]
        public string LanguageCode { get; set; }
        public bool? Active { get; set; }
    }
}