// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Juwon.Models
{
    public partial class Mold
    {
        public Mold()
        {
            Bom = new HashSet<Bom>();
        }

        [Key]
        public int MoldId { get; set; }
        [Required]
        [StringLength(10)]
        public string MoldCode { get; set; }
        [Required]
        [StringLength(50)]
        public string MoldName { get; set; }
        [StringLength(100)]
        public string Image { get; set; }
        [Column(TypeName = "decimal(3, 3)")]
        public decimal? UnitPrice { get; set; }
        [StringLength(3)]
        public string Currency { get; set; }
        [Required]
        public bool? Active { get; set; }
        [Column(TypeName = "datetime2(0)")]
        public DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        [Column(TypeName = "datetime2(0)")]
        public DateTime? ModifiedDate { get; set; }
        public int? ModifiedBy { get; set; }

        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(UserInfo.Mold))]
        public virtual UserInfo CreatedByNavigation { get; set; }
        [InverseProperty("Mold")]
        public virtual ICollection<Bom> Bom { get; set; }
    }
}