// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Juwon.Models
{
    public partial class Part
    {
        public Part()
        {
            BomDetail = new HashSet<BomDetail>();
            Material = new HashSet<Material>();
        }

        [Key]
        public int PartId { get; set; }
        [Required]
        [StringLength(3)]
        public string PartCode { get; set; }
        [Required]
        [StringLength(50)]
        public string PartName { get; set; }
        [StringLength(100)]
        public string PartDescription { get; set; }
        [Required]
        public bool? Active { get; set; }
        [Column(TypeName = "datetime2(0)")]
        public DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        [Column(TypeName = "datetime2(0)")]
        public DateTime? ModifiedDate { get; set; }
        public int? ModifiedBy { get; set; }

        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(UserInfo.Part))]
        public virtual UserInfo CreatedByNavigation { get; set; }
        [InverseProperty("Part")]
        public virtual ICollection<BomDetail> BomDetail { get; set; }
        [InverseProperty("Part")]
        public virtual ICollection<Material> Material { get; set; }
    }
}