// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Juwon.Models
{
    public partial class Permission
    {
        public Permission()
        {
            RolePermission = new HashSet<RolePermission>();
        }

        [Key]
        public int ID { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [StringLength(4)]
        public string PermissionCategory { get; set; }
        [StringLength(150)]
        public string Description { get; set; }
        public bool? Active { get; set; }

        [InverseProperty("Permission")]
        public virtual ICollection<RolePermission> RolePermission { get; set; }
    }
}