// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Juwon.Models
{
    public partial class Process
    {
        [Key]
        public int ProcessId { get; set; }
        [Required]
        [StringLength(5)]
        public string ProcessCode { get; set; }
        [Required]
        [StringLength(50)]
        public string ProcessName { get; set; }
        [StringLength(100)]
        public string ProcessDescription { get; set; }
        [StringLength(100)]
        public string ProcessNote { get; set; }
        [Required]
        public bool? Active { get; set; }
        [Column(TypeName = "datetime2(0)")]
        public DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        [Column(TypeName = "datetime2(0)")]
        public DateTime? ModifiedDate { get; set; }
        public int? ModifiedBy { get; set; }

        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(UserInfo.Process))]
        public virtual UserInfo CreatedByNavigation { get; set; }
    }
}