// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Juwon.Models
{
    public partial class QCRel
    {
        [Key]
        public int Id { get; set; }
        public int QCMasterId { get; set; }
        public int QCDetailId { get; set; }
        public bool Active { get; set; }
        [Column(TypeName = "datetime2(0)")]
        public DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        [Column(TypeName = "datetime2(0)")]
        public DateTime? ModifiedDate { get; set; }
        public int? ModifiedBy { get; set; }

        [ForeignKey(nameof(QCDetailId))]
        [InverseProperty("QCRel")]
        public virtual QCDetail QCDetail { get; set; }
        [ForeignKey(nameof(QCMasterId))]
        [InverseProperty("QCRel")]
        public virtual QCMaster QCMaster { get; set; }
    }
}