// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Juwon.Models
{
    public partial class RoleMenu
    {
        [Key]
        public int RoleID { get; set; }
        [Key]
        public int MenuID { get; set; }

        [ForeignKey(nameof(MenuID))]
        [InverseProperty("RoleMenu")]
        public virtual Menu Menu { get; set; }
        [ForeignKey(nameof(RoleID))]
        [InverseProperty("RoleMenu")]
        public virtual Role Role { get; set; }
    }
}