// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Juwon.Models
{
    public partial class RoleUser
    {
        [Key]
        public int UserID { get; set; }
        [Key]
        public int RoleID { get; set; }

        [ForeignKey(nameof(RoleID))]
        [InverseProperty("RoleUser")]
        public virtual Role Role { get; set; }
        [ForeignKey(nameof(UserID))]
        [InverseProperty(nameof(UserInfo.RoleUser))]
        public virtual UserInfo User { get; set; }
    }
}