// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Juwon.Models
{
    public partial class RolePermission
    {
        [Key]
        public int RoleID { get; set; }
        [Key]
        public int PermissionID { get; set; }

        [ForeignKey(nameof(PermissionID))]
        [InverseProperty("RolePermission")]
        public virtual Permission Permission { get; set; }
        [ForeignKey(nameof(RoleID))]
        [InverseProperty("RolePermission")]
        public virtual Role Role { get; set; }
    }
}