// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Juwon.Models
{
    public partial class Supplier
    {
        [Key]
        public int SupplierId { get; set; }
        [Required]
        [StringLength(100)]
        public string SupplierName { get; set; }
        [StringLength(200)]
        public string SupplierAddress { get; set; }
        [StringLength(100)]
        public string SupplierUrl { get; set; }
        [StringLength(100)]
        public string SupplierEmail { get; set; }
        [StringLength(20)]
        public string SupplierPhone { get; set; }
        [Required]
        public bool? Active { get; set; }
        [Column(TypeName = "datetime2(0)")]
        public DateTime? CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        [Column(TypeName = "datetime2(0)")]
        public DateTime? ModifiedDate { get; set; }
        public int? ModifiedBy { get; set; }

        [ForeignKey(nameof(CreatedBy))]
        [InverseProperty(nameof(UserInfo.Supplier))]
        public virtual UserInfo CreatedByNavigation { get; set; }
    }
}