// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Juwon.Models
{
    public partial class UserInfo
    {
        public UserInfo()
        {
            Area = new HashSet<Area>();
            AreaCategory = new HashSet<AreaCategory>();
            Bom = new HashSet<Bom>();
            BomDetailCreatedByNavigation = new HashSet<BomDetail>();
            BomDetailMaterial = new HashSet<BomDetail>();
            Buyer = new HashSet<Buyer>();
            Color = new HashSet<Color>();
            Destination = new HashSet<Destination>();
            Location = new HashSet<Location>();
            LocationCategory = new HashSet<LocationCategory>();
            Material = new HashSet<Material>();
            Mold = new HashSet<Mold>();
            Part = new HashSet<Part>();
            Process = new HashSet<Process>();
            QCDetail = new HashSet<QCDetail>();
            QCMaster = new HashSet<QCMaster>();
            Recycle = new HashSet<Recycle>();
            RoleUser = new HashSet<RoleUser>();
            Season = new HashSet<Season>();
            Supplier = new HashSet<Supplier>();
            Vendor = new HashSet<Vendor>();
            VendorCategory = new HashSet<VendorCategory>();
        }

        [Key]
        public int ID { get; set; }
        [Required]
        [StringLength(20)]
        public string Username { get; set; }
        [Required]
        [StringLength(32)]
        public string Password { get; set; }
        [StringLength(100)]
        public string Name { get; set; }
        [StringLength(150)]
        public string Address { get; set; }
        [StringLength(90)]
        public string Email { get; set; }
        [StringLength(11)]
        public string Phone { get; set; }
        public int? WarehouseID { get; set; }
        public int? LocationID { get; set; }
        public bool? Active { get; set; }
        [Column(TypeName = "datetime2(0)")]
        public DateTime? CreatedDate { get; set; }
        [StringLength(20)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "datetime2(0)")]
        public DateTime? ModifiedDate { get; set; }
        [StringLength(20)]
        public string ModifiedBy { get; set; }

        [InverseProperty("CreatedByNavigation")]
        public virtual ICollection<Area> Area { get; set; }
        [InverseProperty("CreatedByNavigation")]
        public virtual ICollection<AreaCategory> AreaCategory { get; set; }
        [InverseProperty("CreatedByNavigation")]
        public virtual ICollection<Bom> Bom { get; set; }
        [InverseProperty(nameof(BomDetail.CreatedByNavigation))]
        public virtual ICollection<BomDetail> BomDetailCreatedByNavigation { get; set; }
        [InverseProperty(nameof(BomDetail.Material))]
        public virtual ICollection<BomDetail> BomDetailMaterial { get; set; }
        [InverseProperty("CreatedByNavigation")]
        public virtual ICollection<Buyer> Buyer { get; set; }
        [InverseProperty("CreatedByNavigation")]
        public virtual ICollection<Color> Color { get; set; }
        [InverseProperty("CreatedByNavigation")]
        public virtual ICollection<Destination> Destination { get; set; }
        [InverseProperty("CreatedByNavigation")]
        public virtual ICollection<Location> Location { get; set; }
        [InverseProperty("CreatedByNavigation")]
        public virtual ICollection<LocationCategory> LocationCategory { get; set; }
        [InverseProperty("CreatedByNavigation")]
        public virtual ICollection<Material> Material { get; set; }
        [InverseProperty("CreatedByNavigation")]
        public virtual ICollection<Mold> Mold { get; set; }
        [InverseProperty("CreatedByNavigation")]
        public virtual ICollection<Part> Part { get; set; }
        [InverseProperty("CreatedByNavigation")]
        public virtual ICollection<Process> Process { get; set; }
        [InverseProperty("CreatedByNavigation")]
        public virtual ICollection<QCDetail> QCDetail { get; set; }
        [InverseProperty("CreatedByNavigation")]
        public virtual ICollection<QCMaster> QCMaster { get; set; }
        [InverseProperty("CreatedByNavigation")]
        public virtual ICollection<Recycle> Recycle { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<RoleUser> RoleUser { get; set; }
        [InverseProperty("CreatedByNavigation")]
        public virtual ICollection<Season> Season { get; set; }
        [InverseProperty("CreatedByNavigation")]
        public virtual ICollection<Supplier> Supplier { get; set; }
        [InverseProperty("CreatedByNavigation")]
        public virtual ICollection<Vendor> Vendor { get; set; }
        [InverseProperty("CreatedByNavigation")]
        public virtual ICollection<VendorCategory> VendorCategory { get; set; }
    }
}